### ISSUE TITLE
gql vs restful 

### ISSUE THREAD

**Issue by hochan222** [transcendence42/RDD#3]
gql vs restful 의견 알려주세요

**Comment by hochan222** [comment]
## REST API

### 장점
- REST API를 사용하여 정보를 가져올 때 항상 완전한 데이터 세트를 얻을 수 있다.
- 단순하다.
- REST는 API를 배포하는 회사의 산업 표준이다.

### 단점
- 특정 엔드 포인트에서 일부 정보를 수집하려면 REST API가 반환하는 필드를 제한 할 수 없다.
- over fetching이 발생한다.

## GraphQL

### 장점
- GraphQL API 는 주로 하나의 Endpoint 를 사용한다.
-  GraphQL은 쿼리 언어를 사용하여 여러 개체에서 각 엔터티 내의 특정 필드에 이르기까지 필요한 항목에 정확하게 요청을 보낼 수 있다.
- 필요한 데이터만 가져오기 때문에 필요한 처리량을 제한할 수 있다.
- RESTful API 로 다양한 기종에서 필요한 정보들을 제공할 수 있다.
- HTTP 응답의 Size 를 줄일 수 있다.
- HTTP 요청의 횟수를 줄일 수 있다.

### 단점
- 프로젝트 종류에 따라서 오버엔지니어링이 될 수 있다.
- 러닝커브
- File 전송 등 Text 만으로 하기 힘든 내용들을 처리하기 복잡하다.
- 재귀적인 Query 가 불가능하다. 
- 고정된 요청과 응답만 필요할 경우에는 Query 로 인해 요청의 크기가 RESTful API 의 경우보다 더 커진다.

## 선택 기준

- GraphQL
  - 서로 다른 모양의 다양한 요청들에 대해 응답할 수 있어야 할 때
  - 대부분의 요청이 CRUD(Create-Read-Update-Delete) 에 해당할 때
- RESTful
  - HTTP 와 HTTPs 에 의한 Caching 을 잘 사용하고 싶을 때
  - File 전송 등 단순한 Text 로 처리되지 않는 요청들이 있을 때
  - 요청의 구조가 정해져 있을 때

**Comment by jwon42** [comment]
제가 찾아본 자료들에 의하면 우리 프로젝트에는 RESTful이 더 적합해 보이지만
GraphQL을 학습해서 잘 사용할 수 있다면 더 간편하게 작업할 수 있을 것 같기도 합니다.
전 일단 **RESTful** 에 1표입니다.

----

**GraphQL**
-  서로 다른 모양의 다양한 요청들에 대해 응답할 수 있어야 할 때
-  대부분의 요청이 CRUD(Create-Read-Update-Delete) 에 해당할 때

**RESTful**
-  HTTP 와 HTTPs 에 의한 Caching 을 잘 사용하고 싶을 때
-  File 전송 등 단순한 Text 로 처리되지 않는 요청들이 있을 때
-  요청의 구조가 정해져 있을 때

**유용한 링크**
GraphQL 개념 잡기 https://tech.kakao.com/2019/08/01/graphql-basic/
GraphQL의 단점과 대안 https://www.bangseongbeom.com/graphql-downsides-alternatives.html

**그 외 참고 자료**
https://hwasurr.io/api/rest-graphql-differences/
https://tech.kakao.com/2019/08/01/graphql-basic/
https://www.holaxprogramming.com/2018/01/20/graphql-vs-restful-api/

**Comment by yechoi42** [comment]
단점에 대한 언급은 많이 없어서 찾아봤습니다. 참고하세요! 

-----

3. GraphQL의 단점
GraphQL의 단점으로 알려진 것들로는 다음과 같은 특징이 있다.

3-1. HTTP 캐싱
HTTP의 캐싱 전략은 각각 URL에 각자의 정책을 설정하는 방식으로 이루어 지는데, RESTful API는 이를 그대로 사용이 가능하다.
그러나 GraphQL은 하나의 URL로 처리하기에, HTTP에서 제공하는 캐싱 전략을 그대로 사용하는 것은 불가능하다.

따라서 GraphQL만의 캐싱 방법을 제공하게 되는데, 대표적으로는 영속쿼리(persisted query), 아폴로엔진(Apollo Engine)등이 있다.


3-2. 파일 업로드
GraphQL은 지속적으로 성장하는 생태계로써, 완성된 명세가 존재하지 않는다. 따라서 이 외의 것들은 직접 개발할 수 밖에 없게 된다.
대표적인 예로 파일업로드가 있는데, 다만 이에 대해 몇가지 대안이 있다.

Base64 인코딩을 사용
Upload를 위해 분리된 API 사용
apollo-upload-server 같이 GraphQL multipart 요청 명세를 구현하는 라이브러리를 사용

3-3. 요청 필터링의 어려움
GraphQL은 클라이언트가 필요한 데이터를 스스로 결정하여 요청하게 된다.
따라서 GraphQL의 다양한 요청형태에서 잘못된 요청을 필터링하기가 까다롭다.

출처: https://owin2828.github.io/devlog/2020/11/12/GraphQL-1.html
